### ISSUE TITLE
Problem when turn on TV

### ISSUE THREAD

**Issue by Drealine** [ollo69/ha-samsungtv-smart#102]
**Describe the bug**
TV won't trun off

**Expected behavior**
Toggle ON Tv

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSio
 - Home Assistant version installed: 2021.9.7
 - Component version installed: 0.4.0
 - Last know working version: NB
 - TV model: UE43NU7025

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/samsungtv_smart/media_player.py:967
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:10:47 (7 occurrences)
Last logged: 19:20:07

[140036236903424] None is not a valid PowerOnMethod
[140036236905824] None is not a valid PowerOnMethod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 121, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1004, in async_turn_on
    await self._async_turn_on()
  File "/config/custom_components/samsungtv_smart/media_player.py", line 988, in _async_turn_on
    if not await self._async_power_on(set_art_mode):
  File "/config/custom_components/samsungtv_smart/media_player.py", line 967, in _async_power_on
    turn_on_method = PowerOnMethod(
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: None is not a valid PowerOnMethod
```

**Comment by ollo69** [comment]
I think that I found the issue, it will be fixed with next release

**Comment by Drealine** [comment]
Ok that's great! Thank you.
I will try your fix by copy the file that you've changed in custom folder and try this.

I will tell you if fix it tomorrow.

**Comment by Drealine** [comment]
Fix ok work great. You can push this to the next release
