### ISSUE TITLE
each action getting error

### ISSUE THREAD

**Issue by sunsgs** [ollo69/ha-samsungtv-smart#11]
Hi there, just installed.
every action i make i get this:
Failed to call service media_player/volume_set. can only concatenate str (not "NoneType") to str

also the status is always off.

Is it also possible to get the current channel i Am viewing?
thanks

**Comment by cooperaj** [comment]
I'm getting this after installation. The logs are full of 

```
2020-04-27 12:29:58 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.samsung_tv fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/config/custom_components/samsungtv_smart/media_player.py", line 546, in async_update
    await self._st.async_device_update()
  File "/config/custom_components/samsungtv_smart/api/smartthings.py", line 292, in async_device_update
    device_volume = int(device_volume) / 100
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by cooperaj** [comment]
I've just commented out the relevant volume lines and manually set volume to work and it all appears to work now.

I don't know why the volume is not set in the data dict but it might be because I have a connected soundbar and have configured the audio out to digital?

**Comment by ollo69** [comment]
Never tried with soudbar, I will.
Anyway I will put a check on the code to avoid possible error, also because volume level from smartthings is not accurate and not used at all...

Thx.

**Comment by ollo69** [comment]
I close this issue because I do not receive any new feedback.

**Comment by cooperaj** [comment]
I pulled this update last night. Still need to check if things are working but I didn't get any immediate error logs which is good.
