### ISSUE TITLE
TV unavailable- back after again reading integration

### ISSUE THREAD

**Issue by pepsonEL** [ollo69/ha-samsungtv-smart#117]
Hi. Form some time i have a problem with this integration and my Samsung OLED TV. After reboot HA i always have unavailable my TV in HA. It back again when i go to Integration and reload integration.... and YV is available.... Why ? Where is a problem ? Please help me.....

In logs i found this:
```
Logger: homeassistant.components.media_player
Source: custom_components/samsungtv_smart/media_player.py:348
Integration: Odtwarzacz mediów (documentation, issues)
First occurred: 08:04:21 (1 occurrences)
Last logged: 08:04:21

Error while setting up samsungtv_smart platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 178, in async_setup_entry
    [SamsungTVDevice(config, entry_id, session, token_file, logo_file)], True
  File "/config/custom_components/samsungtv_smart/media_player.py", line 263, in __init__
    self._channel_list = SamsungTVDevice._load_param_list(
  File "/config/custom_components/samsungtv_smart/media_player.py", line 348, in _load_param_list
    result = json.loads(src_list)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 75 (char 74)
```

**Comment by ollo69** [comment]
Seems that you have a malformed source/app/channel list in your `configuration.yaml`. Reloading application after HA boot skip loading info in `configuration.yaml` and for this reason it do not fail.

**Comment by pepsonEL** [comment]
I have this in HA
samsungtv_smart:
  - host: 192.168.xx.xx
    channel_list: '{"TVP1HD": "1@TV", "TVP2HD": "2@TV", "TVN HD": "33@TV", "Polsat": "4@TV", }'

**Comment by pepsonEL** [comment]
When remove it all is ok.....

**Comment by ollo69** [comment]
I Think it could be:

```
samsungtv_smart:

  - host: 192.168.xx.xx
    channel_list: {"TVP1HD": "1@TV", "TVP2HD": "2@TV", "TVN HD": "33@TV", "Polsat": "4@TV"}
```

The error probably is the comma at the end, you can validate using an on-line JSON parser.

**Comment by pepsonEL** [comment]
Very very thanks works ok,
