### ISSUE TITLE
Connection drops ~30 seconds after integration loads

### ISSUE THREAD

**Issue by edurfee** [ollo69/ha-samsungtv-smart#118]
After loading the integration, my TV (Samsung Q90r) shows as on and I can do power/volume/etc. in the media player - full functionality. After about 30 seconds or so, the TV shows a powered off state and I lose it. Interestingly enough, the SmartThings connections work just fine (change source vol up/down) - just not the non-ST functions. I think this log entry corresponds to my disconnects. As a workaround I am using the native integration alongside your fork so I can power my TV on/off and use your fork's SmartThings integration to change inputs directly & control volume. It works but I'd rather just have the one integration (yours). Any idea if this is related to the disconnect or is there somewhere else I should be digging into? 

`This error originated from a custom integration.

Logger: root
Source: custom_components/samsungtv_smart/api/samsungws.py:352
Integration: SamsungTV Smart (documentation, issues)
First occurred: 3:57:46 PM (9 occurrences)
Last logged: 4:40:04 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 305, in run_forever
    try:
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 66, in read
    def read(self, sock, read_callback, check_callback):
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 269, in read
    raise WebSocketException("Ensure ping_interval > ping_timeout")
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 230, in teardown
    and each element is argument of sock.setsockopt.
AttributeError: 'Thread' object has no attribute 'isAlive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 352, in _client_remote_thread
    self._ws_remote.run_forever(
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 311, in run_forever
    self.sock.settimeout(getdefaulttimeout())
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 230, in teardown
    and each element is argument of sock.setsockopt.
AttributeError: 'Thread' object has no attribute 'isAlive'
`

**Comment by ollo69** [comment]
`isAlive` is deprecated method replaced with `is_alive`. Version older than `0.58.0` of [websocket-client](https://github.com/websocket-client/websocket-client) library still use `isAlive`. Probably you have installed an integration that is forcing use of old library version. You must remove that integration and upgrade `websocket-client` in your HA env at least to version `0.58.0` to fix this issue.

**Comment by edurfee** [comment]
Nice, thanks! I'll track the integration down. Kudos for that super fast response!
