### ISSUE TITLE
HTTPS URL content type as image (jpg) not working.

### ISSUE THREAD

**Issue by exotsk** [ollo69/ha-samsungtv-smart#135]
i am try to cast image to TV from hassio HTTPS link and catch errror  AttributeError: 'Resource' object has no attribute 'url'.

after changinng link type to any HTTP, i have a picture on screen.
mp3 url type also only http

syntax.

service: media_player.play_media
data:
  media_content_id: http://www.psy.msu.ru/illusion/upside_down/horse.jpg
  media_content_type: url
target:
  entity_id: media_player.samsung65.

**Comment by ollo69** [comment]
Please provide HA logs with error

**Comment by exotsk** [comment]
Logger: aiohttp.server
Source: components/dlna_dmr/media_player.py:742
First occurred: 10:12:30 (2 occurrences)
Last logged: 10:12:30

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/aiohttp.py", line 308, in _handle_request
    status = await self.event_handler.handle_notify(headers, body)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/event_handler.py", line 171, in handle_notify
    service.notify_changed_state_variables(changes)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/client.py", line 423, in notify_changed_state_variables
    self.on_event(self, changed_state_variables)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/profiles/dlna.py", line 354, in _on_event
    dlna_handle_notify_last_change(state_variable)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/profiles/dlna.py", line 211, in dlna_handle_notify_last_change
    service.notify_changed_state_variables(changes_0)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/client.py", line 423, in notify_changed_state_variables
    self.on_event(self, changed_state_variables)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/profiles/dlna.py", line 365, in _on_event
    self.on_event(service, state_variables)
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 449, in _on_event
    self.async_schedule_update_ha_state(force_refresh)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 694, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 611, in _async_write_ha_state
    if (entity_picture := self.entity_picture) is not None:
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 890, in entity_picture
    return self.media_image_local
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 895, in media_image_local
    if (image_hash := self.media_image_hash) is None:
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 508, in media_image_hash
    if (url := self.media_image_url) is not None:
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 742, in media_image_url
    return self._device.media_image_url
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/profiles/dlna.py", line 1181, in media_image_url
    return absolute_url(device_url, res.url)
AttributeError: 'Resource' object has no attribute 'url'

**Comment by exotsk** [comment]
Logger: homeassistant
Source: components/dlna_dmr/media_player.py:742
First occurred: 10:12:38 (1 occurrences)
Last logged: 10:12:38

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 735, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 611, in _async_write_ha_state
    if (entity_picture := self.entity_picture) is not None:
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 890, in entity_picture
    return self.media_image_local
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 895, in media_image_local
    if (image_hash := self.media_image_hash) is None:
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 508, in media_image_hash
    if (url := self.media_image_url) is not None:
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 742, in media_image_url
    return self._device.media_image_url
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/profiles/dlna.py", line 1181, in media_image_url
    return absolute_url(device_url, res.url)
AttributeError: 'Resource' object has no attribute 'url'

**Comment by exotsk** [comment]
service: media_player.play_media
data:
  media_content_id: https://dl.zamp3.net/files/track/2022/02/pozhar-kvorum-pasha-odessit-sh-kera-kashemirovye-vorotnichki.mp3
  media_content_type: url
target:
  entity_id: media_player.samsung65



Logger: homeassistant
Source: components/dlna_dmr/media_player.py:742
First occurred: 10:13:48 (1 occurrences)
Last logged: 10:13:48

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 735, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 611, in _async_write_ha_state
    if (entity_picture := self.entity_picture) is not None:
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 890, in entity_picture
    return self.media_image_local
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 895, in media_image_local
    if (image_hash := self.media_image_hash) is None:
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 508, in media_image_hash
    if (url := self.media_image_url) is not None:
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 742, in media_image_url
    return self._device.media_image_url
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/profiles/dlna.py", line 1181, in media_image_url
    return absolute_url(device_url, res.url)
AttributeError: 'Resource' object has no attribute 'url'

**Comment by exotsk** [comment]
no image, music, video HTTPS link accepted with "url" content type.
http (internal, external) links played normally

**Comment by ollo69** [comment]
I do no not see in the log any reference to this integration. Are you sure that you are using this integration? Seems that the problem in in `components/dlna_dmr/media_player.py`.
I also suppose that he problem could be that you don't have `https` protocol configured for your HA instance.
Please verify component you are using, if not related to this please remember  to close this issue.

**Comment by exotsk** [comment]
I removed the DMR component, the error from the logs is missing, even in the extended log there is nothing, but the situation has not changed. Any https link causes a connection error on TV. replacing the link with http shows the source (picture, music). https TV links in your browser opens without problems, plays music. HA is fully configured to https, and all accesses to it even from the local network are made using an external link, resources expanded by HA by the link/local/are displayed outside. I don't understand what the problem is. But I assume that TV gets some wrong format in the case of https

**Comment by ollo69** [comment]
With last release I changed the way that play_media service with media_type URL is managed. Can you try if this fix the issue?

**Comment by exotsk** [comment]
I don`t know, but it`s not work in http now

![image](https://user-images.githubusercontent.com/54969124/159159789-e9f07090-110e-4b23-a999-5f89320b1f99.png)

2022-03-20 18:18:48 ERROR (MainThread) [custom_components.samsungtv_smart.media_player] Unsupported media type: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/elephantsdream.mp4
2022-03-20 18:19:00 ERROR (MainThread) [custom_components.samsungtv_smart.media_player] Unsupported media type: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/elephantsdream.mp4

**Comment by ollo69** [comment]
Content type and content id must be inverted!!!

**Comment by exotsk** [comment]
Yes! =) my mistake =) i will check now

**Comment by ollo69** [comment]
Is the samsung browser app installed on your TV?

**Comment by exotsk** [comment]
Ye
![photo_2022-03-21_12-17-50](https://user-images.githubusercontent.com/54969124/159208805-da96d9d3-8baf-4aaf-a1dc-9acfa82ad075.jpg)
![photo_2022-03-21_12-17-36](https://user-images.githubusercontent.com/54969124/159208806-31102c18-4fd9-4b00-875b-675f05486994.jpg)
s

**Comment by ollo69** [comment]
Is the browser app available in the list of your TV sources? Are you able to launch the browser from the integration?

**Comment by exotsk** [comment]
no, i have only tv and hdmi

**Comment by exotsk** [comment]
no reaction on this

 "entity_id": "media_player.samsungtv",
  "media_content_type": "browser",
  "media_content_id": "https://www.google.com"
![image](https://user-images.githubusercontent.com/54969124/159426064-870b9d7d-4c24-44d8-a72c-db6b96eb7a07.png)

**Comment by sbur83** [comment]
> no reaction on this
> 
> "entity_id": "media_player.samsungtv", "media_content_type": "browser", "media_content_id": "https://www.google.com" ![image](https://user-images.githubusercontent.com/54969124/159426064-870b9d7d-4c24-44d8-a72c-db6b96eb7a07.png)

It's probably a separate issue; I haven't been able to get open browser page to work either. Following, this would be handy.
