### ISSUE TITLE
Can't turn off the TV

### ISSUE THREAD

**Issue by thierry-rhone** [ollo69/ha-samsungtv-smart#161]
**Describe the bug**
for some time the turn of the TV no longer works with the message.
```

custom_components.samsungtv_smart.api.samsungws.ConnectionFailure: {'event': 'ms.channel.unauthorized'}
```
 I haven't changed anything though.

**Screenshots**
![image](https://user-images.githubusercontent.com/65720627/164986975-8814ff48-8ef4-4602-882d-9ec94b5f4752.png)

**Environment details:**
 - Environment :
 - home assistant supervised
 - Home Assistant version installed:
 - core-2022.4.6
 - Component version installed:
 - the last
 - Last know working version:
 - TV model:
Samsung UE65NU7105
**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/samsungtv_smart/api/samsungws.py:844
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:26:19 (3 occurrences)
Last logged: 18:32:41

[281473353362640] {'event': 'ms.channel.unauthorized'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/universal/media_player.py", line 536, in async_turn_off
    await self._async_call_service(SERVICE_TURN_OFF, allow_override=True)
  File "/usr/src/homeassistant/homeassistant/components/universal/media_player.py", line 256, in _async_call_service
    await async_call_from_config(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 167, in async_call_from_config
    await hass.services.async_call(**params, blocking=blocking, context=context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1205, in async_turn_off
    result = await self.hass.async_add_executor_job(self._turn_off)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1189, in _turn_off
    self.send_command(cmd_power_off)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 867, in send_command
    ret_val = self._ws.send_key(
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 857, in send_key
    return self._ws_send(
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 276, in _ws_send
    connection = self.open()
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 844, in open
    raise ConnectionFailure(response)
custom_components.samsungtv_smart.api.samsungws.ConnectionFailure: {'event': 'ms.channel.unauthorized'}

```

**Additional context**

**Comment by thierry-rhone** [comment]
Solved, it was a problem of authorization on the tv
