### ISSUE TITLE
Status failing to update on 2020 Samsung Frame

### ISSUE THREAD

**Issue by sh00t2kill** [ollo69/ha-samsungtv-smart#173]
**Describe the bug**
Status is out of sync

**Expected behavior**
Status should be in sync

**Screenshots**
NA

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Hassio
 - Home Assistant version installed: 2022.07.2
 - Component version installed: Latest
 - Last know working version: Not Sure
 - TV model: 2020 Frame 65

**Output of HA logs**
2022-07-09 15:41:47 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.sitting_room_frame fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/config/custom_components/samsungtv_smart/media_player.py", line 802, in async_update
    await self._update_media()
  File "/config/custom_components/samsungtv_smart/media_player.py", line 923, in _update_media
    media_image_url = await self._logo.async_find_match(new_media_title)
  File "/config/custom_components/samsungtv_smart/logo.py", line 280, in async_find_match
    await self._async_ensure_latest_path_file()
  File "/config/custom_components/samsungtv_smart/logo.py", line 166, in _async_ensure_latest_path_file
    update_file = not await aiopath.path.isfile(self._logo_file_download_path)
AttributeError: module 'aiofiles.os' has no attribute 'path'
```

```

**Additional context**
It will sometimes update after a HA restart, but eventually goes out of sync again.

**Comment by ccorderod** [comment]
Same issue here. TV is a QE49Q6FNA.
`2022-07-09 13:09:11 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.tv_cocina fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/config/custom_components/samsungtv_smart/media_player.py", line 802, in async_update
    await self._update_media()
  File "/config/custom_components/samsungtv_smart/media_player.py", line 923, in _update_media
    media_image_url = await self._logo.async_find_match(new_media_title)
  File "/config/custom_components/samsungtv_smart/logo.py", line 280, in async_find_match
    await self._async_ensure_latest_path_file()
  File "/config/custom_components/samsungtv_smart/logo.py", line 166, in _async_ensure_latest_path_file
    update_file = not await aiopath.path.isfile(self._logo_file_download_path)
AttributeError: module 'aiofiles.os' has no attribute 'path'`

Two others TVs using same component do not show this error: QE65Q75TATXXC and UE65KS8000

**Comment by ollo69** [comment]
Probably some integration is hard pinning [aiofiles](https://github.com/Tinche/aiofiles) version lower than `0.8.0`. Check manifest of other custom integration, or at least provide list of installed custom integration so that i can check.

**Comment by sh00t2kill** [comment]
Good catch. SmartIR is tagging 0.6.0

**Comment by ollo69** [comment]
I think that an issue to SmartIR should be opened, asking to not hard pin `aiofiles` (it is always better avoid hard pinning).
As work-around you can try to manual install `aiofiles` (`pip install aiofiles`) in your HA environment, hoping that HA on startup do not force rollback to previous version.

**Comment by sh00t2kill** [comment]
I have opened an issue with SmartIR. For the momemt i have changed it on my env, and the samsung error has dissapeared.

Thanks!
