### ISSUE TITLE
2022 Frame TV art mode not supported

### ISSUE THREAD

**Issue by Fulladorn** [ollo69/ha-samsungtv-smart#212]
Hello,

It appears that the 2022 Frame TV is not supported. When adding the TV with the optional SmartThings token (also tried w/o), the power button in HA will only cycle between on(regularly on, can see TV etc.) and off(art mode). I'm unable to completely power down the TV.

I've tried the advanced setting for frame TV's with the same result, both enabled and disabled.

Calling the set_art_mode service does nothing to the TV, it does not set it to art mode. media_player.turn_off just sets the TV back to art mode.

**Comment by danielducu** [comment]
I've investigated this for quite some time now ... it seams that the SmartThings rest api no longer supports the newer models of Samsung TV's. This integration works for other devices and older TV's but not the newer. The api somehow updates but with a delay of sometimes even a month.  I've given up on this...

**Comment by ollo69** [comment]
`set_art_mode` is not based on `SmartThings` but on `WebSocket` communication. Unfortunaty I don't have a new model and is not in plan to buy a new one, so I'm not able to do any tests. A programmer with a new TV could do this, I don't know if someone in this thread.

**Comment by Jds5nz** [comment]
I have a 2022 Frame TV and had issues with service samsungtv_smart.set_art_mode not working as I expected as well.
I am still new to the guys of Home Assistant, however I created a button card, with entity as the media_player.[mytv]
Tap action: Toggle
And using that, seems to go to Art Mode.

**Comment by stukjedevelopment** [comment]
I have the 2022 Frame TV. I just switched from the original samsung tizen integration to this one. With the original the TV just turned off, but now I can only toggle between on and art mode. Is there anything I can do to help to fix this issue?

**Comment by webjib** [comment]
I can confirm that the default Samsung intégration can switch off my The Frame 2022.

**Comment by ollo69** [comment]
> I can confirm that the default Samsung intégration can switch off my The Frame 2022.
> 
> edit: I’ve checked integration source code, and for The Frame, the turn_off function is sending this command: SendRemoteKey.hold("KEY_POWER", 3)
> 
> Could it be possible to have this behavior as well?

As you already checked, the native integration does nothing more than send a different command, while this integration manage the possible state changes between off -> art mode -> on.
I will further investigate on this, but is not possible to simply implement same behavior of native integration.

**Comment by webjib** [comment]
Maybe you could offer a way to customize the turn_off sequence. For example: allowing users to use a custom « send_key » sequence instead of the default behavior.

**Comment by Fulladorn** [comment]
Could you use both integrations at once and define TV as 2 entities?

**Comment by ollo69** [comment]
> Maybe you could offer a way to customize the turn_off sequence. For example: allowing users to use a custom « send_key » sequence instead of the default behavior.

This is already possible, just use the option to hold key, and you can turn off your TV

> also, the original integration from jaruba states:
> 
> is_frame_tv:

This is a configuration option that this integration do not have. But because I can understand if frameTV is supported just queying the TV (as native integration do), I just have to adjust the code for this specific condition. Please be patient, it will come...

> Could you use both integrations at once and define TV as 2 entities?

What do you mean???

**Comment by webjib** [comment]
> > Maybe you could offer a way to customize the turn_off sequence. For example: allowing users to use a custom « send_key » sequence instead of the default behavior.
> 
> This is already possible, just use the option to hold key, and you can turn off your TV

I can’t find such an option in the settings. I know I can send the Hold sequence to turn off the TV, but that’s not the default behavior of the integration. Thus I can’t use the power key in the media card. When we uncheck the Art Mode checkbox in the settings, what command is sent to the TV when we turn it off? Could you send a hold sequence instead?

**Comment by Fulladorn** [comment]
> > Could you use both integrations at once and define TV as 2 entities?
> 
> What do you mean???

Could you used both this integration and the native integration at the same time?

**Comment by ollo69** [comment]
> I can’t find such an option in the settings. I know I can send the Hold sequence to turn off the TV, but that’s not the default behavior of the integration

For this need modification, I will write here when it will be ready

 

> When we uncheck the Art Mode checkbox in the settings, what command is sent to the TV when we turn it off? Could you send a hold sequence instead?

That option is used only when art mode is detected, but because on this new TVs this detection not working anymore, that check in option is useless.

**Comment by webjib** [comment]
Thank you very much!

**Comment by ollo69** [comment]
With last released version it should be possible to properly turn-off 2022 Frame TV. Please test it and give me your feed-back.

**Comment by Fulladorn** [comment]
Running into an error when setting up the integration freshly.

`2023-01-23 18:03:08.400 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up samsungtv_smart platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 187, in async_setup_entry
    SamsungTVDevice(
  File "/config/custom_components/samsungtv_smart/media_player.py", line 365, in __init__
    self._update_config_options(True)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 467, in _update_config_options
    self._ws.update_app_list(self._app_list)
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 338, in update_app_list
    self._app_list = dict(app_list)
TypeError: 'NoneType' object is not iterable`

I got the "Allow" notification on the TV followed by a success on the configuration flow UI. However, no entity is listed.

**Comment by mecolmg** [comment]
> Running into an error when setting up the integration freshly. Error below & redacted diagnostics attached.
> 
> I got the "Allow" notification on the TV followed by a success on the configuration flow UI. However, no entity is listed.

+1, I've fixed this temporarily by manually setting the app list:

1. On the integrations page, click "configure"
2. Check "Show options menu", then click "Submit"
3. Click "Applications list configuration"
4. I used the example config from the docs, then click "Submit": 
```
Netflix: "11101200001"
YouTube: "111299001912"
Spotify: "3201606009684"
```
5. Click "Save options and exit"
6. Reload the integration

**Comment by ollo69** [comment]
Stupid error🤦‍♂️. Fixed in 0.10.1

**Comment by Fulladorn** [comment]
> Stupid error🤦‍♂️. Fixed in ~0.10.1~ ... **0.10.2**

Works!

Confirmed both **On -> Art -> Off** and **On -> Off**. 


Turn on has some weird behavior but _works,_ seems like if you go from **Off -> Art Mode** it is instead **Off -> Last state** (either On or Art), if you call the service again it will go to art. The turn_on service behaves a bit odd but seems to generally not work. Not sure if this is something that is fixable or a limitation.

**Comment by peter-dorn** [comment]
Works, thanks! Keep up the good job!

**Comment by ollo69** [comment]
@Fulladorn,

because with this TV model I'm not able to determinate the real TV state, for Art Mode service I can only send a power command when I know that TV is turned-on to switch from art-mode to on and viceversa. Related to turn-on, it just use a wake-up-on-lan command and behavior can change. You can also use the integration option to:

1) configure to send wake-up packet multiple time
2) try using SmartThings as alternative method to turn on the TV (normally is better when TV is wireless connected, but could not work at all...)

**Comment by Fulladorn** [comment]
> @Fulladorn,
> 
> because with this TV model I'm not able to determinate the real TV state, for Art Mode service I can only send a power command when I know that TV is turned-on to switch from art-mode to on and viceversa. Related to turn-on, it just use a wake-up-on-lan command and behavior can change. You can also use the integration option to:
> 
> 1. configure to send wake-up packet multiple time
> 2. try using SmartThings as alternative method to turn on the TV (normally is better when TV is wireless connected, but could not work at all...)

Totally understand, works for me, great update. Closing issue as 0.10.2 resolves it.
