### ISSUE TITLE
Power control problem

### ISSUE THREAD

**Issue by HA-TB303** [ollo69/ha-samsungtv-smart#22]
**Describe the bug**
Since the recent update to 0.3.0 I can not power on/off the TV reliably anymore.

**Environment details:**
 - Environment (HASSIO, on a Intel NUC
 - Home Assistant version installed: 0.110.1
 - Component version installed: 0.3.0
 - Last know working version: ? (previous version)
 - TV model: Samsung Q90R

I use this TV network and HDMI only, NO TV channels active via cable or satellite. 

**Output of HA logs**
```
Logger: homeassistant.components.websocket_api.http.connection.140449134994960
Source: custom_components/samsungtv_smart/api/samsungws.py:638
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:16:52 (7 occurrences)
Last logged: 16:27:39

{'event': 'ms.channel.unauthorized'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 453, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    await result
  File "/config/custom_components/samsungtv_smart/media_player.py", line 783, in async_turn_off
    await self.hass.async_add_executor_job(self._turn_off)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 777, in _turn_off
    self.send_command("KEY_POWER")
  File "/config/custom_components/samsungtv_smart/media_player.py", line 592, in send_command
    key_code, key_press_delay, "Press" if press else "Click"
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 662, in send_key
    key_press_delay,
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 243, in _ws_send
    connection = self.open()
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 638, in open
    raise exceptions.ConnectionFailure(response)
custom_components.samsungtv_smart.api.exceptions.ConnectionFailure: {'event': 'ms.channel.unauthorized'}
```

**Comment by ollo69** [comment]
You have problem only in power control? Others command work properly?

**Comment by HA-TB303** [comment]
I just removed the integration so I can not say for sure, since I mostly just use on/off in automations.

I tried reinstalling the integration, but now it fails.
![image](https://user-images.githubusercontent.com/9609805/82735039-10d28300-9d1f-11ea-8b48-69c606ad4a27.png)

![image](https://user-images.githubusercontent.com/9609805/82735055-28aa0700-9d1f-11ea-9b30-825bc4d9f04c.png)

![image](https://user-images.githubusercontent.com/9609805/82735066-3b244080-9d1f-11ea-8c35-e94e822a3238.png)

I don't get any prompt on my TV:

![image](https://user-images.githubusercontent.com/9609805/82735086-7a529180-9d1f-11ea-8e2f-fcb378a7f08b.png)

**Comment by HA-TB303** [comment]
I just removed the "home assistant connection" from the samsung TV settings and tried again.

All is fine now. I just remains a bit strange that the update of the component seems to have caused the issue, since there where no further changes.

**Comment by ollo69** [comment]
Good to hear that now is ok,
Sometimes token loose validity, and I still do not exactly understand the reason.
Anyway I will make some additional test to try to find a way to better manage this case.
