### ISSUE TITLE
Update for media_player.samsung_tv fails in v0.11.1

### ISSUE THREAD

**Issue by tlamoureux24** [ollo69/ha-samsungtv-smart#222]
Hello,

With the last update v0.11.1 i have lot's of error in HA logs.

Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.helpers.entity
Source: custom_components/samsungtv_smart/media_player.py:564
Integration: SamsungTV Smart (documentation, issues)
First occurred: 09:35:39 (13 occurrences)
Last logged: 09:38:24

Update for media_player.samsung_tv fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    raise exc
  File "/config/custom_components/samsungtv_smart/media_player.py", line 847, in async_update
    self._get_running_app()
  File "/config/custom_components/samsungtv_smart/media_player.py", line 564, in _get_running_app
    self._running_app = st_running_app or DEFAULT_APP
UnboundLocalError: local variable 'st_running_app' referenced before assignment

Rolling back to v0.11.0 solved the issue.

Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Interface utilisateur : 20230110.0 - latest

Thanks.

**Comment by ollo69** [comment]
Yes, sorry, fixed in [v0.11.2](https://github.com/ollo69/ha-samsungtv-smart/releases/tag/v0.11.2)

**Comment by tlamoureux24** [comment]
Thank you.
I update but another bug in v0.11.2, i open a new issue.
