### ISSUE TITLE
Unable to create WebSocket connection with this Samsung TV device.

### ISSUE THREAD

**Issue by milandzuris** [ollo69/ha-samsungtv-smart#239]
**Describe the bug**
Unable to create WebSocket connection with this Samsung TV device.
![image](https://user-images.githubusercontent.com/42905545/224553475-ee4af360-8639-4e75-b991-e0b528ade3de.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Proxmox VM Hass OS
 - Home Assistant version installed: 2023.3.3
 - Last know working version: on PRI
 - TV model:

**Output of HA logs**
This error originated from a custom integration.

Logger: custom_components.samsungtv_smart
Source: custom_components/samsungtv_smart/__init__.py:409
Integration: SamsungTV Smart (documentation, issues)
First occurred: 15:56:21 (8 occurrences)
Last logged: 16:05:16

Web socket connection to SamsungTV 192.168.0.30 failed

Logger: homeassistant.components.websocket_api.http.connection
Source: components/smartthings/switch.py:54
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 06:13:43 (1 occurrences)
Last logged: 06:13:43

[139886414043008] 409, message='Conflict', url=URL('https://api.smartthings.com/v1/devices/6a96ab38-b59f-489e-b8a8-344049c85a14/commands')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/smartthings/switch.py", line 54, in async_turn_on
    await self._device.switch_on(set_status=True)
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/device.py", line 1022, in switch_on
    result = await self.command(component_id, Capability.switch, Command.on)
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/device.py", line 825, in command
    response = await self._api.post_device_command(
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 147, in post_device_command
    return await self.post(API_DEVICE_COMMAND.format(device_id=device_id), data)
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 395, in post
    return await self.request("post", self._api_base + resource, data=data)
  File "/usr/local/lib/python3.10/site-packages/pysmartthings/api.py", line 376, in request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 409, message='Conflict', url=URL('https://api.smartthings.com/v1/devices/6a96ab38-b59f-489e-b8a8-344049c85a14/commands')

**Comment by ollo69** [comment]
One of the error reported in the log is not related to this integration but to HA SmartThings integration. It is not clear to me (but is possible) that there is a conflict between this 2 integrations (I see that the error message reported by SmartThings is "conflict") You could try to disable or remove SmartThings integration to see if this fix the issue.
Anyway seems that this integration fails to connect to websocket, and this should not be related to SmartThings. Is your TV and HA in the same subnet? Different subnet do not work due to a SamsungTV limitation. Was the TV on during integration configuration? Did you see the permission popup on TV screen while you was configuring integration?

**Comment by shurakr** [comment]
Is your TV and HA in the same subnet? - yes
Did you see the permission popup on TV screen while you was configuring integration? - yes
Was the TV on during integration configuration? - yes

**Comment by christiangonre** [comment]
If anyone else face this problem like me, I fixed it doing a "hard restart" of the TV. To do this, you need to press the stop button in the TV controller for a few seconds and it will restart the TV, after this the install works great.

**Comment by markyuk** [comment]
I had the same problem just now and hadn't realised ... it was super simple ... make sure the TV is turned on, and when you submit the popup for credentials, there will be a popup on the TV to accept Home Assistant - Allow and it worked.

**Comment by PA-64** [comment]
> I had the same problem just now and hadn't realised ... it was super simple ... make sure the TV is turned on, and when you submit the popup for credentials, there will be a popup on the TV to accept Home Assistant - Allow and it worked.

**Pop UP** --> Accept on TV screen
