### ISSUE TITLE
samsung off status

### ISSUE THREAD

**Issue by pafftis** [ollo69/ha-samsungtv-smart#241]
Good afternoon. I don't know what this problem is related to. Perhaps due to the update, before that everything worked fine. My TV UE55MU6100 always has the status OFF. 

Home assistant 2023.02.05
SamsungTV Smart 11.6 version

**Comment by ollo69** [comment]
Please provide diagnostic

**Comment by pafftis** [comment]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 873, in _ping_thread_method
    self._check_remote()
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 890, in _check_remote
    self._get_running_app()
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 951, in _get_running_app
    self._get_app_status(app.app_id, app.app_type)
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 702, in _get_app_status
    self._ws_send(
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 414, in _ws_send
    connection.send(payload)
  File "/usr/local/lib/python3.10/site-packages/websocket/_app.py", line 239, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 525, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.10/site-packages/websocket/_socket.py", line 170, in send
    return _send()
  File "/usr/local/lib/python3.10/site-packages/websocket/_socket.py", line 147, in _send
    return sock.send(data)
  File "/usr/local/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)`

**Comment by pafftis** [comment]
How can I remove the log ?
