### ISSUE TITLE
Open Browser Page doesn't work

### ISSUE THREAD

**Issue by giof94is** [ollo69/ha-samsungtv-smart#243]
**Describe the bug**
A clear and concise description of what the bug is:
I've followed the instruction on the git main page for "Open Browser Page" but the following service call doesn't work:
service: media_player.play_media
data: {
  "entity_id": "media_player.samsung_tv",
  "media_content_type": "url", (also tried with "browser")
  "media_content_id": "https://www.google.com"}

while the similar "Cast to YouTube" feature fortunately worked.
Also tried with the same without "enqueue" option, as it's said "Note: enqueue is required, or the service will open the video using TV Web Browser" but the issue remains.
The same if the browser is already opened/closed on the TV.

The "internet" app is configured also as a source (Internet: org.tizen.browser), and switching to it regularly open the tizen browser on the TV.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.
Calling the following should open the web browser on the TV navigating to the specified url (also tried with different ones and with different approaches (es. http, https, without www etc.):
service: media_player.play_media
data: {
  "entity_id": "media_player.samsung_tv",
  "media_content_type": "url",  (also tried with "browser")
  "media_content_id": "https://www.google.com"
  }

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HA Supervised running on docker on RP4
 - Home Assistant version installed: 2023.3.5
 - Component version installed: latest 11.6
 - Last know working version: never worked
 - TV model: UE75AU7170UXZT 

**Output of HA logs**
Paste the relavant output of the HA log here.
no log output. But, with a wrong url it says "url is relative but not starting with /".

**Comment by giof94is** [comment]
@ollo69 thanks for your amazing work! Do you have any suggestions?

**Comment by ollo69** [comment]
On some models urls or browser media type could not work. In an case attach diagnostics so that I can better analyze your configuration.

**Comment by giof94is** [comment]
@ollo69 thanks man, here the diagnostic.
Note that I've also tried to add browser to source list and it seems working, it was a tentative because for example cast to Youtube without its app added as source doesn't work neither.

{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2023.3.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "6.1.19-v8+",
    "supervisor": "2023.03.3",
    "host_os": "Debian GNU/Linux 11 (bullseye)",
    "docker_version": "23.0.1",
    "chassis": "",
    "run_as_root": true
  },
  "custom_components": {
    ...
    "hacs": {
      "version": "1.31.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
...
    "samsungtv_smart": {
      "version": "0.11.6",
      "requirements": [
        "websocket-client!=1.4.0,>=0.58.0",
        "wakeonlan>=2.0.0",
        "aiofiles>=0.8.0",
        "casttube>=0.2.1"
      ]
    },
    ...
  },
  "integration_manifest": {
    "domain": "samsungtv_smart",
    "name": "SamsungTV Smart",
    "integration_type": "device",
    "documentation": "https://github.com/ollo69/ha-samsungtv-smart",
    "issue_tracker": "https://github.com/ollo69/ha-samsungtv-smart/issues",
    "requirements": [
      "websocket-client!=1.4.0,>=0.58.0",
      "wakeonlan>=2.0.0",
      "aiofiles>=0.8.0",
      "casttube>=0.2.1"
    ],
    "dependencies": [],
    "codeowners": [
      "@jaruba",
      "@ollo69",
      "@screwdgeh"
    ],
    "config_flow": true,
    "iot_class": "cloud_polling",
    "version": "0.11.6",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "ad7c660f34dfd79409c4b9d79e350e0f",
      "version": 1,
      "domain": "samsungtv_smart",
      "title": "samsung_tv_75_salotto_ci (SmartThings)",
      "data": {
        "host": "192.168.1.237",
        "name": "samsung_tv_75_salotto_ci",
        "port": 8002,
        "ws_name": "samsung_tv_75_salotto_ci",
        "token": "**REDACTED**",
        "id": "92a2a56b-a640-4fa4-9eb0-592ff264ee47",
        "device_name": "Samsung 75 Salotto",
        "device_model": "UE75AU7170UXZT",
        "device_os": "Tizen",
        "mac": "**REDACTED**",
        "api_key": "**REDACTED**",
        "device_id": "a846249f-4e28-e04f-2a5e-e8f5c3bc53bf"
      },
      "options": {
        "use_st_status_info": true,
        "use_st_channel_info": true,
        "show_channel_number": false,
        "logo_option": 2,
        "use_local_logo": true,
        "power_on_method": 1,
        "app_launch_method": 1,
        "wol_repeat": 1,
        "ping_port": 9197,
        "use_mute_check": false,
        "dump_apps": true,
        "toggle_art_mode": false,
        "sync_turn_off": [],
        "sync_turn_on": [],
        "app_list": {
          "Netflix": "3201907018807/org.tizen.netflix-app",
          "YouTube": "111299001912",
          "Spotify": "3201606009684",
          "Prime Video": "3201910019365/org.tizen.ignition",
          "Internet": "org.tizen.browser"
        },
        "channel_list": {},
        "source_list": {}
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "92a2a56b-a640-4fa4-9eb0-592ff264ee47",
      "disabled_by": null
    },
    "device": {
      "name": "samsung_tv_75_salotto_ci",
      "name_by_user": null,
      "model": "UE75AU7170UXZT (Samsung 75 Salotto)",
      "manufacturer": "Samsung Electronics",
      "sw_version": "Tizen",
      "disabled": false,
      "disabled_by": null,
      "entities": {
        "media_player.samsung_tv_75_salotto_ci": {
          "name": null,
          "original_name": "samsung_tv_75_salotto_ci",
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "tv",
          "icon": null,
          "original_icon": "mdi:television",
          "unit_of_measurement": null,
          "state": {
            "state": "on",
            "attributes": {
              "source_list": [
                "TV",
                "Netflix",
                "YouTube",
                "Spotify",
                "Prime Video",
                "Internet"
              ],
              "sound_mode_list": [
                "Amplificazione",
                "Standard",
                "Suono adattivo"
              ],
              "volume_level": 0.21,
              "is_volume_muted": false,
              "media_content_type": "video",
              "media_title": "TV8 HD",
              "app_id": "TV/HDMI",
              "source": "TV/HDMI",
              "sound_mode": "Standard",
              "entity_picture_local": "/api/media_player_proxy/media_player.samsung_tv_75_salotto_ci?token=a31839a868c5c2b2fb9f96eb9b15028b98c9a96188a4a43c5bad1b2b51db2749&cache=abc52d1d10b87287",
              "ip_address": "192.168.1.237",
              "picture_mode": "Dinamica",
              "picture_mode_list": [
                "Dinamica",
                "FILMMAKER MODE",
                "Film",
                "Naturale",
                "Standard"
              ],
              "device_class": "tv",
              "entity_picture": "**REDACTED**",
              "icon": "mdi:television",
              "friendly_name": "samsung_tv_75_salotto_ci",
              "supported_features": 221117
            },
            "last_changed": "2023-04-02T11:15:06.652355+00:00",
            "last_updated": "2023-04-02T11:17:06.632127+00:00"
          }
        }
      }
    }
  }
}

**Comment by giof94is** [comment]
Ho @ollo69 any news? Thanks man!

**Comment by giof94is** [comment]
Keep it up

**Comment by giof94is** [comment]
Any news on that?

**Comment by weierles** [comment]
Same here.
I tried with the script:
`service: media_player.play_media
target:
  entity_id: media_player.samsung_the_frame_43_2
data:
  media_content_type: url
  media_content_id: "https://www.google.com"`

and get a Error:
  File "/usr/local/lib/python3.11/site-packages/didl_lite/didl_lite.py", line 103, in _ensure_required_properties
    raise DidlLiteException(key + " is mandatory")
didl_lite.didl_lite.DidlLiteException: **bookmarked_object_id is mandatory**

**Comment by weierles** [comment]
I solved it with the Code:

service: media_player.select_source
data:
  source: Browser
target:
  device_id: e6axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by giof94is** [comment]
Hi @weierles thanks!

This seems just to open the browser app on the TV, but have you manage also the way to sent an url to open the browser directly on that url?

**Comment by weierles** [comment]
I can open the browser, but it only works because I set the requested page as default start page. 
And the page is not refreshed, that is sad.

If I try to open a specific page using media_content_type: url
I got:

2023-07-22 20:17:30.090 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: bookmarked_object_id is mandatory
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 74, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 643, in async_play_media
    didl_metadata = await self._device.construct_play_media_metadata(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 987, in construct_play_media_metadata
    item = didl_item_type(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/didl_lite/didl_lite.py", line 81, in __init__
    self._ensure_required_properties(strict, properties)
  File "/usr/local/lib/python3.11/site-packages/didl_lite/didl_lite.py", line 103, in _ensure_required_properties
    raise DidlLiteException(key + " is mandatory")
didl_lite.didl_lite.DidlLiteException: bookmarked_object_id is mandatory
2023-07-22 20:17:30.095 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139921391790352] Error handling message: Unknown error (unknown_error) dave from 192.168.1.105 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 678, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1533, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 410, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 454, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 477, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 74, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 643, in async_play_media
    didl_metadata = await self._device.construct_play_media_metadata(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 987, in construct_play_media_metadata
    item = didl_item_type(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/didl_lite/didl_lite.py", line 81, in __init__
    self._ensure_required_properties(strict, properties)
  File "/usr/local/lib/python3.11/site-packages/didl_lite/didl_lite.py", line 103, in _ensure_required_properties
    raise DidlLiteException(key + " is mandatory")
didl_lite.didl_lite.DidlLiteException: bookmarked_object_id is mandatory
/bin/sh: False: not found

**Comment by giof94is** [comment]
Any news on that?

**Comment by Jonseed** [comment]
I also have the same problem on Samsung The Frame TV...
