### ISSUE TITLE
Incorrect MAC address format

### ISSUE THREAD

**Issue by mlbs-dev** [ollo69/ha-samsungtv-smart#25]
**Describe the bug**
When trying to turn the TV on I get incorrect MAC address format. I have a The Frame TV 43.

I have tried with and without mac in configuration. I have tried writing the mac as "xx:xx:xx:xx:xx:xx" and "XX:XX:XX:XX:XX:XX" and also with dashes like "XX-XX-XX-XX-XX-XX".

In core.device_registry the mac is set to "None" by the integration, like:

```
"connections": [
  [
    "mac",
    "None"
  ]
]
```

Tried changing it to the mac address, like (sot sure if that is correct):

```
"connections": [
  [
    "mac",
    "address"
  ]
]
```

Got it to work once, but some upgrades and reboots later I can't get it to work like that either. Not sure which version I got working.

**Expected behavior**
That it is turned on.

**Output of HA logs**
```
Incorrect MAC address format
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/config/custom_components/samsungtv_smart/media_player.py", line 826, in async_turn_on
    await self.hass.async_add_executor_job(self._turn_on)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 821, in _turn_on
    send_magic_packet(self._mac)
  File "/usr/local/lib/python3.7/site-packages/wakeonlan.py", line 74, in send_magic_packet
    packet = create_magic_packet(mac)
  File "/usr/local/lib/python3.7/site-packages/wakeonlan.py", line 38, in create_magic_packet
    raise ValueError('Incorrect MAC address format')
ValueError: Incorrect MAC address format

```

**Comment by ollo69** [comment]
How you configure the TV? Using configuration.yaml or User Interface.
Please try commenting any line on configuration.yaml related to the TV, delete the integration in User Interface, reboot and reconfigure integration with User Interface. Be sure that TV is turned on during configuration, mac-address should be automatically detected after confirming permission prompt on tv screen.

**Comment by mlbs-dev** [comment]
Works after a complete purge and new setup from GUI. I have used both ways back and forth and I guess that is what has confused the integration.

At some point though there was this in core.device_registry:

```
"connections": [
  [
    "mac",
    "address",
    "mac",
    "None"
  ]
]
```
And then it didn't work but I can't recreate it.

I guess we can close it and I will reopen if the error comes back and I can see a reason for it.
