### ISSUE TITLE
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

### ISSUE THREAD

**Issue by Olen** [ollo69/ha-samsungtv-smart#36]
**Describe the bug**
This is an older (2016) model, and it seems to close the websocket connection when the TV is turned off.

This causes an exception when the TV is turned back on:

Also, the TV is not detected as "on" after this happens:
```
2020-09-01 20:57:59 WARNING (MainThread) [custom_components.samsungtv_smart.media_player] SamsungTV Smart - Detected fake power on, status not updated                                        
```
I lowered the "Delay power on" to 0 seconds, to see if that helps.

**Expected behavior**

On and off state should be detected without exceptions

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):  HA Core
 - Home Assistant version installed: 0.114.4
 - Component version installed: Latest from HACS
 - Last know working version:
 - TV model: UE55KS7005

**Output of HA logs**
Paste the relavant output of the HA log here.

```
2020-09-01 20:56:15 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.stue_tv fails
Traceback (most recent call last):                                                                                                                                                            
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 263, in async_update_ha_state
    await self.async_device_update()                                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 454, in async_device_update                                                                                             
    await self.async_update()  # type: ignore                                                                                                                                                 
  File "/config/custom_components/samsungtv_smart/media_player.py", line 631, in async_update                                                                                                 
    result = await self.hass.async_add_executor_job(self._ping_device)                                                                                                                        
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run                                                                                                               
    result = self.fn(*self.args, **self.kwargs)                                                                                                                                               
  File "/config/custom_components/samsungtv_smart/media_player.py", line 408, in _ping_device                                                                                                 
    self._ws.get_running_app()                                                                                                                                                                
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 672, in get_running_app                                                                                             
    self._get_app_status(app.app_id, app.app_type)                                                                                                                                            
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 498, in _get_app_status                                                                                             
    self._ws_send(                                                                                                                                                                            
  File "/config/custom_components/samsungtv_smart/api/samsungws.py", line 256, in _ws_send                                                                                                    
    connection.send(payload)                                                                                                                                                                  
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 154, in send                                                                                                          
    raise WebSocketConnectionClosedException(                                                                                                                                                 
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.           

```

**Additional context**

**Comment by Olen** [comment]
This might actually be due to a conflict with the "parent" component "samsung-tizen" which I had not disabled before installing this.
I guess that component closed the websocket (HA probably reuses it).
But anyhow - maybe a "try/catch" around line 256 in samsungws.py to reconnect if the connection has been closed should be added?

**Comment by ollo69** [comment]
For sure having 2 component that connect to the TV with same IP create issue, anyway I will add a try catch as suggested in next release to restart connections if for some reason are closed.
Related to the issue that TV is not detected as "on", you should try to disable the option "Use volume mute status to detect fake power ON".

**Comment by Olen** [comment]
Removing the other component seems to have solved the problem with disconnects.
I also found the "Use volume mute status", so after turning that off the TV is correctly detected as on.

My only issue now is that when the TV is sleeping (after power off for more than a few minutes) I am unable to turn it back on using the integration. But this might be because of the Ubiquiti WiFi, which I have read that can have issues with Wake on Lan (Wake on Wifi).
(I have the same issue with all three Samsung Integrations so I don't believe the problem is the integrations).

So you can close this bug, and keep up the good work.
