### ISSUE TITLE
KeyError: 'volume'

### ISSUE THREAD

**Issue by kuradi** [ollo69/ha-samsungtv-smart#40]
**Describe the bug**
Basically all is working what im expect but logs are flooded with errors.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): hassio
 - Home Assistant version installed: 0.115.2
 - Component version installed: latest
 - Last know working version: tba
 - TV model:  UE50TU7172UXXH

**Output of HA logs**

```
2020-09-22 02:10:51 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.tvsamsung fails


Traceback (most recent call last):


  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state


    await self.async_device_update()


  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 469, in async_device_update


    await self.async_update()  # type: ignore


  File "/config/custom_components/samsungtv_smart/media_player.py", line 617, in async_update


    await self._st.async_device_update(use_channel_info)


  File "/config/custom_components/samsungtv_smart/api/smartthings.py", line 326, in async_device_update


    device_volume = data["main"]["volume"]["value"]


KeyError: 'volume'


```

**Additional context**

**Comment by ollo69** [comment]
Do you have some external device connected like soundbar to play audio?

**Comment by kuradi** [comment]
yes, im using external audio via digital audio output.

**Comment by ollo69** [comment]
This should be fixed with last release

**Comment by ollo69** [comment]
Closing this issue due to inactivity from long time.
