### ISSUE TITLE
Error doing job: Task exception was never retrieved - WebSocketProtocolException

### ISSUE THREAD

**Issue by holdestmade** [ollo69/ha-samsungtv-smart#6]
With new version 0.1.6 getting this in log when trying to switch off and won;t switch off the TV:

Logger: homeassistant.core
Source: custom_components/samsungtv_smart/websockets.py:152
First occurred: 9:50:11 AM (1 occurrences)
Last logged: 9:50:11 AM
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 599, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 710, in async_toggle
    await self.async_turn_off()
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 526, in async_turn_off
    await self.hass.async_add_job(self.turn_off)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/samsungtv_smart/media_player.py", line 718, in turn_off
    self.send_command("KEY_POWER")
  File "/config/custom_components/samsungtv_smart/media_player.py", line 532, in send_command
    self._ws.send_key(payload, key_press_delay)
  File "/config/custom_components/samsungtv_smart/websockets.py", line 181, in send_key
    key_press_delay
  File "/config/custom_components/samsungtv_smart/websockets.py", line 109, in _ws_send
    self.open()
  File "/config/custom_components/samsungtv_smart/websockets.py", line 152, in open
    response = self._process_api_response(self.connection.recv())
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 383, in recv_frame
    frame.validate(self.skip_utf8_validation)
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 182, in validate
    raise WebSocketProtocolException("Invalid close opcode.")
websocket._exceptions.WebSocketProtocolException: Invalid close opcode.
```

**Comment by holdestmade** [comment]
Found I needed to authorize the TV again and all works fine
