### ISSUE TITLE
websocket._exceptions.WebSocketProtocolException: Invalid close opcode.

### ISSUE THREAD

**Issue by mikelitka** [ollo69/ha-samsungtv-smart#63]
**Describe the bug**
When trying to power off I get the following error: websocket._exceptions.WebSocketProtocolException: Invalid close opcode.

**Expected behavior**
TV should power off.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HA installed via pip on VM 
 - Home Assistant version installed:  2021.3.2
 - Component version installed: v0.3.30
 - Last know working version:
 - TV model: UN50MU6300 

**Output of HA logs**
Paste the relavant output of the HA log here.
Logger: homeassistant.components.websocket_api.http.connection
Source: lib/python3.8/site-packages/websocket/_abnf.py:182
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:23:31 PM (2 occurrences)
Last logged: 5:44:45 PM

[140446081075040] Invalid close opcode.
[140446055765616] Invalid close opcode.
Traceback (most recent call last):
  File "/common/apps/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/common/apps/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/common/apps/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/common/apps/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/common/apps/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/common/apps/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/common/apps/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/common/apps/homeassistant/custom_components/samsungtv_smart/media_player.py", line 1061, in async_turn_off
    result = await self.hass.async_add_executor_job(self._turn_off)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/common/apps/homeassistant/custom_components/samsungtv_smart/media_player.py", line 1045, in _turn_off
    self.send_command(cmd_power_off)
  File "/common/apps/homeassistant/custom_components/samsungtv_smart/media_player.py", line 761, in send_command
    ret_val = self._ws.send_key(
  File "/common/apps/homeassistant/custom_components/samsungtv_smart/api/samsungws.py", line 775, in send_key
    return self._ws_send(
  File "/common/apps/homeassistant/custom_components/samsungtv_smart/api/samsungws.py", line 252, in _ws_send
    connection = self.open()
  File "/common/apps/homeassistant/custom_components/samsungtv_smart/api/samsungws.py", line 746, in open
    response = self._process_api_response(connection.recv())
  File "/common/apps/homeassistant/lib/python3.8/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/common/apps/homeassistant/lib/python3.8/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/common/apps/homeassistant/lib/python3.8/site-packages/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "/common/apps/homeassistant/lib/python3.8/site-packages/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/common/apps/homeassistant/lib/python3.8/site-packages/websocket/_abnf.py", line 383, in recv_frame
    frame.validate(self.skip_utf8_validation)
  File "/common/apps/homeassistant/lib/python3.8/site-packages/websocket/_abnf.py", line 182, in validate
    raise WebSocketProtocolException("Invalid close opcode.")
websocket._exceptions.WebSocketProtocolException: Invalid close opcode.

**Additional context**
I am able to recreate this right now.

**Comment by mikelitka** [comment]
@ollo69 any feedback you can provide on this issue?

**Comment by ollo69** [comment]
This error is normally caused by ws communication between TV and HA not working properly.
Is your TV in the same subnet of HA? Normally using different subnet not work due to Samsung limitation.
Did you configure properly the integration? Did you authorize HA on the TV during integration setup?

**Comment by mikelitka** [comment]
@ollo69 thanks for the insight. it was an issue with the allow list. smh. appreciate it.
