### ISSUE TITLE
Unable to Power On.

### ISSUE THREAD

**Issue by BobRathke** [ollo69/ha-samsungtv-smart#72]
**Describe the bug**
After installing, I can turn the TV off, but not on. Installed using Using Smartthings token

**Environment details:**
HASSIO 2021.4 Supervised

**Output of HA logs**
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/samsungtv_smart/api/smartthings.py:305
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:10:06 PM (3 occurrences)
Last logged: 2:37:18 PM

[547392824176] 409, message='Conflict', url=URL('https://api.smartthings.com/v1/devices/7f3796d5-b1b7-4a86-aeee-e7ee9fa0c5c5/commands')
[547404508944] 409, message='Conflict', url=URL('https://api.smartthings.com/v1/devices/7f3796d5-b1b7-4a86-aeee-e7ee9fa0c5c5/commands')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1029, in async_turn_on
    await self._async_turn_on()
  File "/config/custom_components/samsungtv_smart/media_player.py", line 1013, in _async_turn_on
    if not await self._async_power_on(set_art_mode):
  File "/config/custom_components/samsungtv_smart/media_player.py", line 997, in _async_power_on
    await self._st.async_turn_on()
  File "/config/custom_components/samsungtv_smart/api/smartthings.py", line 445, in async_turn_on
    await self._async_send_command(data_cmd)
  File "/config/custom_components/samsungtv_smart/api/smartthings.py", line 305, in _async_send_command
    async with self._session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 625, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 409, message='Conflict', url=URL('https://api.smartthings.com/v1/devices/7f3796d5-b1b7-4a86-aeee-e7ee9fa0c5c5/commands')

```

```

**Additional context**

**Comment by ollo69** [comment]
Does smartthings app on your phone able to turn on TV?
