### ISSUE TITLE
No config flow ?¿

### ISSUE THREAD

**Issue by Tyrian81** [ollo69/ha-samsungtv-smart#85]
**Describe the bug**
added the  integration through hacs, but when trying to add it in HA  through integrations , it says error in config flow...

**Expected behavior**
opening config UI

**Environment details:**
TV (QE55Q64RALXXN)
HA latest version
running on ARM CPU

**Output of HA logs**
Logger: homeassistant.util.package
Source: util/package.py:96
First occurred: 14:44:53 (3 occurrences)
Last logged: 14:50:26

Unable to install package websocket-client==1.0.1: ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: '__pycache__' WARNING: You are using pip version 20.2.4; however, version 21.1.2 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

Logger: aiohttp.server
Source: requirements.py:163
First occurred: 14:44:53 (3 occurrences)
Last logged: 14:50:26

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 76, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 693, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 374, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
    await _async_process_integration(hass, integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 99, in _async_process_integration
    await async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 163, in async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for samsungtv_smart not found: ['websocket-client==1.0.1'].

**Comment by ollo69** [comment]
Issue here is not in integration but a problem in your HA environment to download the correct library version. 
What version of HA are you using? What is your OS?

**Comment by Tyrian81** [comment]
> Issue here is not in integration but a problem in your HA environment to download the correct library version.
> What version of HA are you using? What is your OS?

2021.6.5 homeassistant

**Comment by ollo69** [comment]
I don't know exactly where is the problem, probably you don't have enough permission.
You need to investigate and fix this:

`Unable to install package websocket-client==1.0.1: ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: 'pycache'`

Not an integration issue.

**Comment by ollo69** [comment]
Closing this issue due to inactivity from long time and because not related to integration.
